### PR TITLE
Use asynchronous tasks to handle querying

### PR DESCRIPTION
**Pull request by aterrype**
Updated to use asynchronous tasks to handle querying

### CODE REVIEW

**Comment by glinesbdev** [comment]
Thanks for pushing this up! I'll review it ASAP!

**Comment by glinesbdev** [comment]
@aterrype what I would like to see is that we `add` async functions but not replace the synchronous ones so that we don't break any other users using this SDK. Also, we will need to update the comments around the async functions. Another convention is that async methods are usually called something like `GetAsync` instead of just `Get`. If you would make these changes, that would be greatly appreciated. Otherwise I would be willing to do that also.

**Comment by aterrype** [comment]
That all makes sense to me. I haven't had time to make those changes but I'll make them when I do.

**Comment by glinesbdev** [comment]
These features were added in PR #15

**Pull request closed without merging**
