### PR TITLE
Feature/v2

### PR DESCRIPTION
**Pull request by Serraniel**
Please notice: This is a draft pull request. It is not finished or in a state in which I would consider it "beta ready". But I probably will not have that much time the next weeks and before somebody does double work I at least want to offer a base as draft if anybody would like to help.
Please also notic: I have not used C# a lot recenlty so I may not be know the latest language sugar yet. Also this is first time I was wrapping a restful api in C# myself, so there is a chance I failed on some of the good practices (if there are some). I started this as a new project instead of simply adjusting the current project to match with the API. So usage of the library will most likely change a lot.

What this is so far:
The current state implements the sets and cards from the v2 api. It can successfully fetch and query them. JSON  parsing technically works with *System.Text.Json* and *System.Net.Http.Json* instead of Newtonsoft JSON. Also contains some basic tests and a simple Query Building utilty. I started it off as a new project and kept the v1 as long it is still in basic development. Would replace it later. 

Open ToDos before I would consider this as "beta-ready":
- [x] docs (I started them in a separated branch already)
- [x] Exception classes
- [x] Complete at least basic funcitonality (some interfaces aren´t even used yet)
- [x] Refactorings and clean-up probably
- [ ] Replacing the old project completly and ajusting namespace maybe
- [ ] Hopefully gather experience how "usable" the API itself is with real projects

More ToDos before this should be released as a stable
- [ ] More tests (they never hurt)
- [ ] Finish implementing all api endpoints (could be done iterative with increasing beta releases)
- [ ] Adding helpful functions (like the Date information as Date objects instead of the strings, the API provides), image downloading maybe, etc.
- [ ] Migration Guide? Would be a tough task for me personally as I actually never used the current v1 project.
- [ ] Probably more which I did not thought about yet. 
- [ ] Alter the readme to match with the v2 lib 

Please feel free to share your thoughts about it or add any other points which I maybe have forgotten about. If you got ideas for improvments share them as well. Maybe would be a good idea to have a branch for the v2 development so multiple people could work on the tasks in parallel, if there are some who want to help.

Update December 18:
- [x] Add new field regulation mark

### CODE REVIEW

**Comment by jaymarvels** [comment]
@Serraniel going to try and review this over the next few days, may need to refactor in places but will know better later

**Comment by Serraniel** [comment]
Thanks @jaymarvels . I also planned to try finishing as much as possible over the next days. Really appreciate your response.

**Comment by jaymarvels** [comment]
Would have preferred to manage the V2 upgrade differently but having a hard time getting much input from Bradyn but we'll do our best.

Really wanted to look into implementing some separation of responsibilities, some lightweight CQRS as well as a good retry process, all which I have ideas for and was planning to do over the next few days also

**Comment by Serraniel** [comment]
Yes I´ll wait for the feedback. Espescially as this is first time for me implementing an api client myself there might few things which probably could have done much better, espescially as I had to work around some things which did not workes as expected so feel free to share your thoughts then when you got the time. 
But feels good to know there already had been ideas for the upgrade. As the draft pr had been silent for so long I felt like I was the only one having ideas about using it 😅

**Comment by jaymarvels** [comment]
I had checked out your draft locally a while ago but been busy with work and life to get any real time on it

**Comment by jaymarvels** [comment]
@Serraniel I am going to close this off as it hasn't been worked on for almost a year. A V2 codebase has been done and is currently in beta testing (see main repo)

**Pull request closed without merging**
